### ISSUE TITLE
Traces are not thread-safe

### ISSUE THREAD

**Issue by ndryden** [LLNL/Aluminum#177]
Saving a trace entry is not thread-safe when `AL_THREAD_MULTIPLE` is set and could trash the trace log.

**Comment by benson31** [comment]
Were one so inclined, a thread-safe logging utility could be used (e.g., [spdlog](https://github.com/gabime/spdlog) -- can be header-only, and it wouldn't grow the LBANN dependency graph, for what that's worth).
