### ISSUE TITLE
MPI communicator should be wrapped with shared_ptr

### ISSUE THREAD

**Issue by naoyam** [LLNL/Aluminum#18]
Copying MPICommunicator does not deepcopy the MPI communicator, so it should be only deleted when no reference exists.

https://github.com/LLNL/Aluminum/blob/0e44e2feebc2714dc8ace55cd376282907d1c14d/src/mpi_impl.hpp#L68

**Comment by ndryden** [comment]
Addressed by the changed semantics in #108.
